insert into stock_attribute values(null, 'PX', 'PE', '10.5', 'single', 'P/E');
insert into stock_attribute values(null, 'AC', 'PE', '21', 'single', 'P/E');
insert into stock_attribute values(null, 'LC', 'PE', '100', 'single', 'P/E');
insert into stock_attribute values(null, 'TEL', 'PE', '9.99', 'single', 'P/E');
insert into stock_attribute values(null, 'PX', 'FiftyTwoWeekLow', '5', 'single', '52Wk Low');
insert into stock_attribute values(null, 'AC', 'FiftyTwoWeekLow', '680.5', 'single', '52Wk Low');
insert into stock_attribute values(null, 'LC', 'FiftyTwoWeekLow', '0.2', 'single', '52Wk Low');
insert into stock_attribute values(null, 'TEL', 'FiftyTwoWeekLow', '2999', 'single', '52Wk Low');
insert into stock_attribute values(null, 'PX', 'FiftyTwoWeekHigh', '7.1', 'single', '52Wk High');
insert into stock_attribute values(null, 'AC', 'FiftyTwoWeekHigh', '900', 'single', '52Wk High');
insert into stock_attribute values(null, 'LC', 'FiftyTwoWeekHigh', '0.5', 'single', '52Wk High');
insert into stock_attribute values(null, 'TEL', 'FiftyTwoWeekHigh', '3566.75', 'single', '52Wk High');
insert into stock_attribute values(null, 'PX', 'LastTradedPrice', '6.5', 'single', 'Last Traded Price');
insert into stock_attribute values(null, 'PX', 'LastTradedDate', '5/1/2015', 'date', 'Last Traded Date');
insert into stock_attribute values(null, 'AC', 'LastTradedPrice', '785', 'single', 'Last Traded Price');
insert into stock_attribute values(null, 'AC', 'LastTradedDate', '5/1/2015', 'date', 'Last Traded Date');