CREATE TABLE ALERTS (
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
SYMBOL TEXT NOT NULL,
PRICELEVEL INTEGER,
PRICE REAL,
VOL_CONJUNCT INTEGER,
VOLUME INTEGER,
MAX_ALERT INTEGER,
ALERT_COUNT INTEGER,
NOTES TEXT);
CREATE TABLE BIDASK(
  ID INTEGER NOT NULL PRIMARY KEY,
  SYMBOL TEXT NOT NULL,
  BIDPRICE REAL,
  BIDVOLUME REAL,
  ASKPRICE REAL,
  ASKVOLUME REAL);
CREATE TABLE INTRADAY(
  SYMBOL TEXT NOT NULL PRIMARY KEY,
  LASTPRICE REAL,
  PCTCHANGE REAL,
  VOLUME REAL,
  STATUS TEXT,
  LASTUPDATE TEXT,
  OPEN REAL,
  HIGH REAL,
  LOW REAL,
  WK52HIGH REAL,
  WK52LOW REAL,
  PERATIO REAL,
  VALUE REAL);
CREATE TABLE STOCKID_MAP (
	ID INTEGER NOT NULL,
	SYMBOL TEXT NOT NULL);

CREATE TABLE STOCKS(
  SYMBOL TEXT NOT NULL PRIMARY KEY,
  DESCRIPTION TEXT,
  ISFAVORITE INTEGER,
  SECURITY_ID INTEGER,
  COMPANY_ID INTEGER,
  LAST_TRADED_PRICE REAL,
  LAST_TRADED_DATE TEXT,
  FREE_FLOAT_LEVEL REAL,
  MARKET_CAPITALIZATION REAL,
  OUTSTANDING_SHARES REAL);

CREATE TABLE STOCK_ATTRIBUTE(	
	SYMBOL TEXT NOT NULL,
	ATTR_KEY TEXT NOT NULL,
	ATTR_VALUE TEXT
	ATTR_TYPE TEXT);  
  
CREATE TABLE INDECES(
	ID TEXT NOT NULL PRIMARY KEY,
	INDEX_SYMBOL TEXT NOT NULL,
	ALT_INDEX_SYMBOL TEXT NOT NULL,
	INDEX_NAME TEXT NOT NULL,
	IS_SECTORAL TEXT,
	SORT_ORDER INTEGER);
	
CREATE TABLE INDEX_STOCKS(
	ID INTEGER NOT NULL PRIMARY KEY,
	SYMBOL TEXT NOT NULL,
	INDEX_ID INTEGER,
	INDEX_WEIGHT REAL);