CREATE TABLE ALERTS (
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
SYMBOL TEXT NOT NULL,
PRICELEVEL INTEGER,
PRICE REAL,
VOL_CONJUNCT INTEGER,
VOLUME INTEGER,
MAX_ALERT INTEGER,
ALERT_COUNT INTEGER,
NOTES TEXT);
CREATE TABLE BIDASK(
  ID INTEGER NOT NULL PRIMARY KEY,
  SYMBOL TEXT NOT NULL,
  BIDPRICE REAL,
  BIDVOLUME REAL,
  ASKPRICE REAL,
  ASKVOLUME REAL);
CREATE TABLE INTRADAY(
  SYMBOL TEXT NOT NULL PRIMARY KEY,
  PRICE REAL,
  PCTCHANGE REAL,
  VOLUME REAL,
  STATUS TEXT,
  LASTUPDATE TEXT,
  OPEN REAL,
  HIGH REAL,
  LOW REAL,
  WK52HIGH REAL,
  WK52LOW REAL,
  PERATIO REAL,
  VALUE REAL);
CREATE TABLE STOCKID_MAP (
ID INTEGER NOT NULL,
SYMBOL TEXT NOT NULL);
CREATE TABLE STOCKS(
  SYMBOL TEXT NOT NULL PRIMARY KEY,
  DESCRIPTION TEXT,
  ISFAVORITE INTEGER);
CREATE TABLE test(
 id integer not null
);
